-- 코드를 입력하세요
SELECT MEMBER_ID, MEMBER_NAME, GENDER, SUBSTRING(DATE_OF_BIRTH, 1) as DATE_OF_BIRTH
FROM MEMBER_PROFILE
WHERE DATE_OF_BIRTH like "%-03-%" and TLNO is not NULL and GENDER = 'W'
ORDER BY MEMBER_ID ASC;
